### ISSUE TITLE
Segmentation model

### ISSUE THREAD

**Issue by cutelucyliu** [Hyuto/yolov8-tfjs#1]
What if I'm using the Yolov8 Segmentation model?

**Comment by Hyuto** [comment]
I think Error might occur XD. 

You can't use YOLOv8-Seg model in this project because it have different output and different way to process. The post process inferencing in segmentation model is more complex. I'm still working on it on other repo, I expect to finish it next week.

**Comment by MaryamBoneh** [comment]
what about pose estimation?
