### ISSUE TITLE
How to use tfjs with backend wasm?

### ISSUE THREAD

**Issue by DaiHaoguang3151** [Hyuto/yolov8-tfjs#10]

**Comment by Hyuto** [comment]
Hello, using tfjs with wasm backend require extra attention, because we need to provide serve tfjs-wasm file too. Maybe using other bundler like webpack might shorten the step, but if you use vite like this project here is the step you need to do:

1. Install more dependencies
    - `@tensorflow/tfjs-backend-wasm` with the same version as `@tensorflow/tfjs`
       Because this project using `@tensorflow/tfjs` version `4.1.0` then we should install `@tensorflow/tfjs-backend-wasm@4.1.0`.
       `yarn add @tensorflow/tfjs-backend-wasm@4.1.0`
    - `vite-plugin-static-copy` as dev dependencies to copy and serve tfjs-wasm file 
      `yarn add -D vite-plugin-static-copy`
2. Update `src/App.jsx`
    Change webgl to wasm
    ```js
    ...
    import * as tf from "@tensorflow/tfjs";
    import '@tensorflow/tfjs-backend-wasm'; // set backend to wasm
    ...
    ```
    Initialize wasm before loading model
    ```js
    tf.setBackend('wasm').then(async () => {
        await tf.ready();
        ...
    ```
3. Update package.json
    Change type to module (required by `vite-plugin-static-copy`)    
    ```json    
    ...
    "type": "module",
    ...
    ```
4. Update vite.config.js
    Setup vite config to apply `vite-plugin-static-copy`
    ```js
    import { defineConfig, normalizePath } from "vite";
    import path from "path";
    import react from "@vitejs/plugin-react";
    import { viteStaticCopy } from "vite-plugin-static-copy";

    // https://vitejs.dev/config/
    export default defineConfig({
      plugins: [
        react(),
        viteStaticCopy({
          targets: [
            {
              src: normalizePath(
                path.resolve(__dirname, "./node_modules/@tensorflow/tfjs-backend-wasm/dist/*.wasm")
              ),
              dest: "./",
            },
          ],
        }),
      ],
      build: {
        chunkSizeWarningLimit: 2000, // handle warning on vendor.js bundle size
      },
      base: "/yolov8-tfjs/",
    });
    ```

**Comment by DaiHaoguang3151** [comment]
I tried to use tfjs with backend wasm several days ago, but it faild.
My Github repo: [face-recognition](https://githubfast.com/DaiHaoguang3151/face-recognition-web_)

[steps:]

yarn install
yarn start
check the console outputs -> "Initialization of backend wasm failed"
![image](https://github.com/Hyuto/yolov8-tfjs/assets/131345009/daa8d987-5d83-4173-8a9b-c61e1c833b26)

**Comment by DaiHaoguang3151** [comment]
#

> Hello, using tfjs with wasm backend require extra attention, because we need to provide serve tfjs-wasm file too. Maybe using other bundler like webpack might shorten the step, but if you use vite like this project here is the step you need to do:
> 
> 1. Install more dependencies
>    
>    * `@tensorflow/tfjs-backend-wasm` with the same version as `@tensorflow/tfjs`
>      Because this project using `@tensorflow/tfjs` version `4.1.0` then we should install `@tensorflow/tfjs-backend-wasm@4.1.0`.
>      `yarn add @tensorflow/tfjs-backend-wasm@4.1.0`
>    * `vite-plugin-static-copy` as dev dependencies to copy and serve tfjs-wasm file
>      `yarn add -D vite-plugin-static-copy`
> 2. Update `src/App.jsx`
>    Change webgl to wasm
>    ```js
>    ...
>    import * as tf from "@tensorflow/tfjs";
>    import '@tensorflow/tfjs-backend-wasm'; // set backend to wasm
>    ...
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Initialize wasm before loading model
>    ```js
>    tf.setBackend('wasm').then(async () => {
>        await tf.ready();
>        ...
>    ```
> 3. Update package.json
>    Change type to module (required by `vite-plugin-static-copy`)
>    ```json
>    ...
>    "type": "module",
>    ...
>    ```
> 4. Update vite.config.js
>    Setup vite config to apply `vite-plugin-static-copy`
>    ```js
>    import { defineConfig, normalizePath } from "vite";
>    import path from "path";
>    import react from "@vitejs/plugin-react";
>    import { viteStaticCopy } from "vite-plugin-static-copy";
>    
>    // https://vitejs.dev/config/
>    export default defineConfig({
>      plugins: [
>        react(),
>        viteStaticCopy({
>          targets: [
>            {
>              src: normalizePath(
>                path.resolve(__dirname, "./node_modules/@tensorflow/tfjs-backend-wasm/dist/*.wasm")
>              ),
>              dest: "./",
>            },
>          ],
>        }),
>      ],
>      build: {
>        chunkSizeWarningLimit: 2000, // handle warning on vendor.js bundle size
>      },
>      base: "/yolov8-tfjs/",
>    });
>    ```

Thanks a lot! It works. 
However, I don't know what's wrong with my repo mentioned above. It would be appreciated if you could take a look!

**Comment by Hyuto** [comment]
I tried to check your repo but I get this.

![image](https://github.com/Hyuto/yolov8-tfjs/assets/64422277/89d191a9-e6df-4769-aad7-64b0f3bdbbd3)

**Comment by DaiHaoguang3151** [comment]
Sorry ! It's [face-recognition](https://github.com/DaiHaoguang3151/face-recognition-web_).
Actually, the problem may be related to face-api.js, which uses tfjs-core.

**Comment by DaiHaoguang3151** [comment]
I tried to uninstall face-api.js and replace it with @vladmandic/face-api. It seems to work.
Thank you for your patience !
