### ISSUE TITLE
Error with custom tfjs model - Error in slice3D - would overflow input.shape

### ISSUE THREAD

**Issue by Matti88** [Hyuto/yolov8-tfjs#7]
Hello.
I have added my own model and it doesn’t seem to work with a similar error message.

<img width="578" alt="image" src="https://github.com/Hyuto/yolov8-tfjs/assets/10582798/705c0fe6-e6ed-4664-9892-aa7bc71a7213">

My suspect is related to the training size. I have trained with 
```python
imgsz=640
```
and perhaps it is too low for the inputs ? shall I change the image size before detecting?

**Comment by Hyuto** [comment]
Hello, 

I don't think that's the issue here because `640` is the default YOLO `imgsz` and this repo preprocessing image to the `tfjs` input automatically. 

Do you update `labels.json` with your custom trained label before running the app?

**Comment by Matti88** [comment]
Hello @Hyuto ,
Thank you very much for the suggestion. That solved the issue!!!
